# Generated by Django 5.0.1 on 2024-02-22 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventario',
            old_name='idempleado',
            new_name='idEmpleado',
        ),
    ]
