# Generated by Django 5.0.1 on 2024-02-22 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='iduser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academico.usuario'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
