# Generated by Django 5.0.1 on 2024-02-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='iddocumento',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
