# Generated by Django 5.0.1 on 2024-03-03 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0002_alter_persona_iddocumento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='idProducto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academico.producto'),
        ),
    ]
