# Generated by Django 5.0.1 on 2024-03-03 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0003_alter_ventas_idproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='idInventario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Academico.inventario'),
        ),
    ]
